//! Emulator + agent + topology registry.
//!
//! Three append-only lists drive the rest of mirage:
//!
//! * [`builtins`] \u2014 registered emulator backends. Each
//!   [`EmulatorSpec`] knows how to describe itself and report
//!   whether its runtime is installed.
//! * [`builtin_agents`] \u2014 named hardware agent definitions
//!   ([`crate::agent::AgentDef`]). Agents are emulator-agnostic
//!   hardware descriptions for one device.
//! * [`builtin_topologies`] \u2014 named system layouts
//!   ([`crate::topology::TopologyDef`]) that arrange agents into
//!   racks/nodes/GPUs.

use crate::common::{MaybeRef, SimpleMap};
use crate::emulator::{EmulatorDef, EmulatorDescription, ExecMode};
use crate::topology::TopologyDef;

// Generated by build.rs: BUILTIN_AGENT_JSON.
include!(concat!(env!("OUT_DIR"), "/agent_builtins.rs"));

/// A registered emulator backend.
#[derive(Debug, Clone, Copy)]
pub struct EmulatorSpec {
    /// Canonical name used on disk and on the CLI.
    pub name: &'static str,
    /// Short human description.
    pub description: &'static str,
    /// Returns `true` if this emulator's runtime is present on the
    /// current machine. Cheap (no network, no spawn): used by the
    /// wizard's default picker.
    pub installed: fn() -> bool,
    /// Returns a long-form description (name + version + blurb).
    pub describe: fn() -> EmulatorDescription,
}

/// Built-in emulator registry. Append-only by intent.
pub fn builtins() -> &'static [EmulatorSpec] {
    &[NOOP, ROCJITSU]
}

/// Lookup an emulator by its canonical name.
pub fn find(name: &str) -> Option<&'static EmulatorSpec> {
    builtins().iter().find(|e| e.name == name)
}

/// The default emulator for new profiles when the user doesn't pick
/// one explicitly. Picks the first installed entry in registration
/// order, falling back to `noop`.
pub fn default_emulator() -> &'static EmulatorSpec {
    builtins()
        .iter()
        .find(|e| !std::ptr::eq(*e, &NOOP) && (e.installed)())
        .unwrap_or(&NOOP)
}

/// Build an [`EmulatorDef`] for the given registry entry, using the
/// supplied system topology.
pub fn make_def(spec: &EmulatorSpec, topology: TopologyDef) -> EmulatorDef {
    EmulatorDef {
        emulator: spec.name.to_string(),
        plugins: Default::default(),
        exec_mode: ExecMode::default(),
        options: SimpleMap::default(),
        topology: MaybeRef::Owned(topology),
    }
}

/// Default topology referenced by a fresh profile: a single GPU
/// driven by the `MI350X` agent.
pub fn default_topology() -> TopologyDef {
    TopologyDef {
        racks: 1,
        nodes_per_rack: 1,
        gpus_per_node: 1,
        agent: MaybeRef::Ref("MI350X".to_string()),
    }
}

/// Curated set of named agents (hardware descriptions) that mirage
/// preloads into `<MIRAGE_CONFIG>/agent/<name>.json`. Sourced from
/// the `agents/*.json` files embedded at build time.
pub fn builtin_agents() -> &'static [(&'static str, &'static str)] {
    BUILTIN_AGENT_JSON
}

/// Curated set of named topologies (system layouts) that mirage
/// preloads into `<MIRAGE_CONFIG>/topology/<name>.json`.
pub fn builtin_topologies() -> Vec<(&'static str, fn() -> TopologyDef)> {
    vec![
        ("MI350X-1x1", || topology(1, 1, 1, "MI350X")),
        ("MI350X-1x8", || topology(1, 1, 8, "MI350X")),
        ("MI350X-2x8", || topology(1, 2, 8, "MI350X")),
        ("MI300X-1x8", || topology(1, 1, 8, "MI300X")),
    ]
}

fn topology(racks: u32, nodes_per_rack: u32, gpus_per_node: u32, agent: &str) -> TopologyDef {
    TopologyDef {
        racks,
        nodes_per_rack,
        gpus_per_node,
        agent: MaybeRef::Ref(agent.to_string()),
    }
}

// =============================================================================
// noop
// =============================================================================

pub const NOOP: EmulatorSpec = EmulatorSpec {
    name: "noop",
    description: "no-op emulator: runs commands directly with no GPU emulation",
    installed: noop_installed,
    describe: noop_describe,
};

fn noop_installed() -> bool {
    true
}

fn noop_describe() -> EmulatorDescription {
    EmulatorDescription {
        name: "noop".to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        description: "Pass-through emulator. Useful for orchestration tests.".to_string(),
    }
}

// =============================================================================
// rocjitsu
// =============================================================================

pub const ROCJITSU: EmulatorSpec = EmulatorSpec {
    name: "rocjitsu",
    description: "ROCm just-in-time GPU emulator (cycle-accurate or functional)",
    installed: rocjitsu_installed,
    describe: rocjitsu_describe,
};

/// rocjitsu is "installed" if the dynamic library `librocjitsu.so`
/// can be found in the mirage emulator cache (extracted by
/// `mirage_rocjitsu::ensure_assets`), via the loader's standard
/// search path, or if the user has set `ROCJITSU_LIB_DIR` /
/// `ROCJITSU_ROOT`.
fn rocjitsu_installed() -> bool {
    let cached = crate::paths::mirage_cache_dir()
        .join("emulator")
        .join("rocjitsu")
        .join("librocjitsu.so");
    if cached.exists() {
        return true;
    }
    if std::env::var_os("ROCJITSU_LIB_DIR").is_some()
        || std::env::var_os("ROCJITSU_ROOT").is_some()
    {
        return true;
    }
    let candidates = [
        "/usr/local/lib/librocjitsu.so",
        "/usr/lib/librocjitsu.so",
        "/usr/lib/x86_64-linux-gnu/librocjitsu.so",
        "/opt/rocm/lib/librocjitsu.so",
    ];
    candidates.iter().any(|p| std::path::Path::new(p).exists())
}

fn rocjitsu_describe() -> EmulatorDescription {
    EmulatorDescription {
        name: "rocjitsu".to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        description: "ROCm GPU simulator (decodes AMDGPU/RISC-V ISA, event-driven PDES core)."
            .to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_lookup() {
        assert_eq!(find("noop").map(|e| e.name), Some("noop"));
        assert_eq!(find("rocjitsu").map(|e| e.name), Some("rocjitsu"));
        assert!(find("bogus").is_none());
    }

    #[test]
    fn noop_is_always_installed() {
        assert!((NOOP.installed)());
    }

    #[test]
    fn default_matches_installation_state() {
        if (ROCJITSU.installed)() {
            assert_eq!(default_emulator().name, "rocjitsu");
        } else {
            assert_eq!(default_emulator().name, "noop");
        }
    }

    #[test]
    fn builtin_agents_and_topologies_nonempty() {
        // Builtin agents are embedded from the agents/ directory.
        assert!(!builtin_agents().is_empty());
        assert!(builtin_topologies().iter().any(|(n, _)| *n == "MI350X-1x1"));
    }
}
