// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/sopc.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace gfx1250 {

SCmpEqI32Sopc::SCmpEqI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpEqI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) == static_cast<int32_t>(ssrc1.read_scalar(wf))));
}

SCmpLgI32Sopc::SCmpLgI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLgI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) < static_cast<int32_t>(ssrc1.read_scalar(wf))) ||
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) > static_cast<int32_t>(ssrc1.read_scalar(wf)))));
}

SCmpGtI32Sopc::SCmpGtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGtI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) > static_cast<int32_t>(ssrc1.read_scalar(wf))));
}

SCmpGeI32Sopc::SCmpGeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGeI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) >= static_cast<int32_t>(ssrc1.read_scalar(wf))));
}

SCmpLtI32Sopc::SCmpLtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLtI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) < static_cast<int32_t>(ssrc1.read_scalar(wf))));
}

SCmpLeI32Sopc::SCmpLeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLeI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (static_cast<int32_t>(ssrc0.read_scalar(wf)) <= static_cast<int32_t>(ssrc1.read_scalar(wf))));
}

SCmpEqU32Sopc::SCmpEqU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpEqU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((ssrc0.read_scalar(wf) == ssrc1.read_scalar(wf)));
}

SCmpLgU32Sopc::SCmpLgU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLgU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(((ssrc0.read_scalar(wf) < ssrc1.read_scalar(wf)) ||
                (ssrc0.read_scalar(wf) > ssrc1.read_scalar(wf))));
}

SCmpGtU32Sopc::SCmpGtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGtU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((ssrc0.read_scalar(wf) > ssrc1.read_scalar(wf)));
}

SCmpGeU32Sopc::SCmpGeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGeU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((ssrc0.read_scalar(wf) >= ssrc1.read_scalar(wf)));
}

SCmpLtU32Sopc::SCmpLtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLtU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((ssrc0.read_scalar(wf) < ssrc1.read_scalar(wf)));
}

SCmpLeU32Sopc::SCmpLeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLeU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((ssrc0.read_scalar(wf) <= ssrc1.read_scalar(wf)));
}

SBitcmp0B32Sopc::SBitcmp0B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp0B32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SBitcmp0B32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((((ssrc0.read_scalar(wf) >> (ssrc1.read_scalar(wf) & 31)) & 1) == 0));
}

SBitcmp1B32Sopc::SBitcmp1B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp1B32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SBitcmp1B32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((((ssrc0.read_scalar(wf) >> (ssrc1.read_scalar(wf) & 31)) & 1) != 0));
}

SBitcmp0B64Sopc::SBitcmp0B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp0B64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SBitcmp0B64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((((static_cast<uint64_t>(ssrc0.read_scalar64(wf)) >> (ssrc1.read_scalar(wf) & 63)) &
                 1ULL) == 0));
}

SBitcmp1B64Sopc::SBitcmp1B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp1B64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SBitcmp1B64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((((static_cast<uint64_t>(ssrc0.read_scalar64(wf)) >> (ssrc1.read_scalar(wf) & 63)) &
                 1ULL) != 0));
}

SCmpEqU64Sopc::SCmpEqU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqU64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpEqU64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((static_cast<uint64_t>(ssrc0.read_scalar64(wf)) ==
                static_cast<uint64_t>(ssrc1.read_scalar64(wf))));
}

SCmpLgU64Sopc::SCmpLgU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgU64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(64, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLgU64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(((static_cast<uint64_t>(ssrc0.read_scalar64(wf)) <
                 static_cast<uint64_t>(ssrc1.read_scalar64(wf))) ||
                (static_cast<uint64_t>(ssrc0.read_scalar64(wf)) >
                 static_cast<uint64_t>(ssrc1.read_scalar64(wf)))));
}

SCmpLtF32Sopc::SCmpLtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLtF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) < std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpLtF16Sopc::SCmpLtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLtF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpEqF32Sopc::SCmpEqF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpEqF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) == std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpEqF16Sopc::SCmpEqF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpEqF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) ==
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpLeF32Sopc::SCmpLeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLeF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) <= std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpLeF16Sopc::SCmpLeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLeF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <=
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpGtF32Sopc::SCmpGtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGtF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) > std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpGtF16Sopc::SCmpGtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGtF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpLgF32Sopc::SCmpLgF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLgF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) < std::bit_cast<float>(ssrc1.read_scalar(wf))) ||
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) > std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpLgF16Sopc::SCmpLgF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpLgF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <
                 util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))) ||
                (util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >
                 util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpGeF32Sopc::SCmpGeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGeF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) >= std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpGeF16Sopc::SCmpGeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpGeF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >=
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpOF32Sopc::SCmpOF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_o_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmpOF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpOF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!std::isnan(std::bit_cast<float>(ssrc0.read_scalar(wf))) &&
                !std::isnan(std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpOF16Sopc::SCmpOF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_o_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmpOF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpOF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!std::isnan(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf)))) &&
                !std::isnan(util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpUF32Sopc::SCmpUF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_u_f32", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmpUF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpUF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((std::isnan(std::bit_cast<float>(ssrc0.read_scalar(wf))) ||
                std::isnan(std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpUF16Sopc::SCmpUF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_u_f16", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCmpUF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpUF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((std::isnan(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf)))) ||
                std::isnan(util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpNgeF32Sopc::SCmpNgeF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nge_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNgeF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNgeF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(std::bit_cast<float>(ssrc0.read_scalar(wf)) >=
                  std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpNgeF16Sopc::SCmpNgeF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nge_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNgeF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNgeF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >=
                  util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpNlgF32Sopc::SCmpNlgF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlg_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNlgF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNlgF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) < std::bit_cast<float>(ssrc1.read_scalar(wf))) ||
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) >
       std::bit_cast<float>(ssrc1.read_scalar(wf))))));
}

SCmpNlgF16Sopc::SCmpNlgF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlg_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNlgF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNlgF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <
                   util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))) ||
                  (util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >
                   util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))))));
}

SCmpNgtF32Sopc::SCmpNgtF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ngt_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNgtF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNgtF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(std::bit_cast<float>(ssrc0.read_scalar(wf)) >
                  std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpNgtF16Sopc::SCmpNgtF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ngt_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNgtF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNgtF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) >
                  util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpNleF32Sopc::SCmpNleF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nle_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNleF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNleF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(std::bit_cast<float>(ssrc0.read_scalar(wf)) <=
                  std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpNleF16Sopc::SCmpNleF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nle_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNleF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNleF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <=
                  util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

SCmpNeqF32Sopc::SCmpNeqF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_neq_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNeqF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNeqF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc(
      (std::bit_cast<float>(ssrc0.read_scalar(wf)) != std::bit_cast<float>(ssrc1.read_scalar(wf))));
}

SCmpNeqF16Sopc::SCmpNeqF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_neq_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNeqF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNeqF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) !=
                util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf)))));
}

SCmpNltF32Sopc::SCmpNltF32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlt_f32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNltF32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(32, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNltF32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(std::bit_cast<float>(ssrc0.read_scalar(wf)) <
                  std::bit_cast<float>(ssrc1.read_scalar(wf)))));
}

SCmpNltF16Sopc::SCmpNltF16Sopc(const MachineInst *inst)
    : Sopc("s_cmp_nlt_f16", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpNltF16Sopc>()),
      ssrc0(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(16, OperandType::OPR_SSRC, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc0 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        16, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 254) {
    const auto *words = reinterpret_cast<const uint32_t *>(inst);
    uint32_t literal_word = sizeof(OpEncoding) / sizeof(uint32_t);
    uint64_t literal64 =
        (static_cast<uint64_t>(words[literal_word + 1]) << 32) | words[literal_word];
    ssrc1 = Operand(16, OperandType::OPR_SIMM64, literal64, true);
  }
}

void SCmpNltF16Sopc::execute_impl(amdgpu::Wavefront &wf) {
  wf.write_scc((!(util::f16_to_f32(static_cast<uint16_t>(ssrc0.read_scalar(wf))) <
                  util::f16_to_f32(static_cast<uint16_t>(ssrc1.read_scalar(wf))))));
}

} // namespace gfx1250
} // namespace rocjitsu
